### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by HotQ** [JeffBelgum/ntp#29]
https://github.com/JeffBelgum/ntp/blob/d9c50ad307a25151a9d3828c8f46387c4020de7b/src/unix_time.rs#L130

**Comment by HotQ** [comment]
` let frac = t.subsec_nanos() as f64 * NTP_SCALE / 1e9; `
instead

**Comment by JeffBelgum** [comment]
Yes, good catch. Thanks for the PR https://github.com/JeffBelgum/ntp/pull/30
