### ISSUE TITLE
Do not use backtrace feature of error-chain

### ISSUE THREAD

**Issue by CryZe** [JeffBelgum/ntp#8]
The backtrace feature barely compiles on half of Rust's targets. Disabling it would allow the usage of this library in more situations. Another option would be making this a feature.

**Comment by JeffBelgum** [comment]
I like the idea of making this an optional feature since I make use of it in my own projects. Is there a tracking issue for that or list of targets that the backtrace features does/does not compile on?

**Comment by JeffBelgum** [comment]
Version `0.3.0` makes backtrace optional under the "backtrace" feature flag.
